 
-- INSERTING MASTER DATA INTO ROOMTYPE TABLE
IF NOT EXISTS(SELECT 1 FROM RoomType WHERE Name='SINGLE')
	INSERT INTO RoomType VALUES('Single',1,GETDATE())
IF NOT EXISTS(SELECT 1 FROM RoomType WHERE Name='DOUBLE')
	INSERT INTO RoomType VALUES('Double',1,GETDATE())

-- INSERTING MASTER DATA INTO BookingStatus TABLE
IF NOT EXISTS(SELECT 1 FROM BookingStatus WHERE Name='Booked')
	INSERT INTO BookingStatus VALUES('Booked',1,GETDATE())
IF NOT EXISTS(SELECT 1 FROM BookingStatus WHERE Name='Not Booked')
	INSERT INTO BookingStatus VALUES('Not Booked',1,GETDATE())

-- INSERTING MASTER DATA INTO ROOMTYPE TABLE
IF NOT EXISTS(SELECT 1 FROM AppUser WHERE UserName='Admin')
	INSERT INTO AppUser(UserName,Password,CreatedDate,IsActive) VALUES('Admin','Admin',GETDATE(),1)



